### ISSUE TITLE
There're several links in POD which not linked properly.

### ISSUE THREAD

**Issue by p16i** [trinitum/perl-File-Flock-Tiny#2]
![screenshot 2014-07-03 17 48 09](https://cloud.githubusercontent.com/assets/1214890/3468551/e8403150-029f-11e4-9c6e-b89efe53804f.png)

![screenshot 2014-07-03 17 48 32](https://cloud.githubusercontent.com/assets/1214890/3468550/e819eb44-029f-11e4-9593-40931ed0763e.png)

**Comment by trinitum** [comment]
Thank you for the report, I fixed the first and the last case, but second and third links are correct, they are working on cpan. Metacpan it seems ignores `X<...>` formatting code and as a result these links are not working. I think it should be fixed in metacpan code.

**Comment by trinitum** [comment]
FYI, I created an issue for metacpan-web: CPAN-API/metacpan-web#1241

**Comment by p16i** [comment]
Cool! :+1:
